backend:
  name: github
  repo: AngelMariages/isern-photography
  branch: main
  base_url: "https://isern-photography.vercel.app/"
  auth_endpoint: "api/auth"
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: settings
    label: Settings
    files:
    - name: collectionOrder
      label: Collection Order
      file: _config/order.md
      fields:
        - label: Collection
          name: collectionOrder
          widget: list
          fields:
            - label: Collection Name
              name: collectionName
              widget: relation
              collection: images
              searchFields: ["title", "image.src"]
              valueField: "image.src"

  - name: "images"
    label: "Image"
    folder: "_posts"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - label: "Image"
        name: "image"
        widget: "object"
        fields:
          - { label: "Image", name: "src", widget: "image" }
          - { label: "Width", name: "width", widget: "hidden", required: false, value: "{{entry.image.width}}" }
          - { label: "Height", name: "height", widget: "hidden", required: false, value: "{{entry.image.height}}" }
