backend:
  name: github
  repo: AngelMariages/isern-photography
  branch: main
  base_url: "https://isern-photography.vercel.app/"
  auth_endpoint: "api/auth"
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: settings
    label: Settings
    files:
    - name: order
      label: Order
      file: _config/order.md
      fields:
        - label: Section order
          widget: list
          name: sectionOrderList
          fields:
            - label: Section name
              name: sectionName
              widget: "select"
              min: 1
              max: 1
              options: ["retrato", "producto", "look-book", "fotos-familia"]
        - label: Posts order
          widget: list
          name: postOrderList
          fields:
            - label: Image Name
              name: postSlug
              widget: relation
              collection: images
              search_fields: ["{{slug}}"]
              value_field: "{{slug}}"

  - name: "images"
    label: "Image"
    folder: "_posts"
    create: true
    slug: "{{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Tags"
        name: "tags"
        widget: "list"
      - label: "Section"
        name: "section"
        widget: "relation"
        collection: "settings"
        search_fields: ["sectionOrderList.*.sectionName"]
        value_field: "sectionOrderList.*.sectionName"
      - label: "Image"
        name: "image"
        widget: "object"
        fields:
          - { label: "Image", name: "src", widget: "image" }
          - { label: "Width", name: "width", widget: "hidden", required: false, value: "{{entry.image.width}}" }
          - { label: "Height", name: "height", widget: "hidden", required: false, value: "{{entry.image.height}}" }
