backend:
  name: github
  repo: AngelMariages/isern-photography
  branch: main
  base_url: "https://isern-photography.vercel.app/"
  auth_endpoint: "api/auth"
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "pages"
    label: "Pages"
    folder: "_posts"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Width", name: "imageWidth", widget: "string", value: "{{entry.image.width}}" }
      - { label: "Height", name: "imageHeight", widget: "string", value: "{{entry.image.height}}" }
